# Generated by Django 4.2.7 on 2023-12-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('otc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MountainPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField()),
                ('coord', models.JSONField(default=dict)),
                ('level', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('mountain_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountapi.mountainpass')),
            ],
        ),
    ]
