# Generated by Django 4.2.7 on 2023-12-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='mountain_user',
        ),
    ]
