# Generated by Django 4.2.7 on 2023-12-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountapi', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.CharField(),
        ),
    ]
